name: Telegram Message Forwarder

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'next_run.txt'

jobs:
  forward:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    
    permissions:
      contents: write

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: pip install -r requirements.txt

      - name: 4. Run the forwarder script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          SOURCE_CHANNELS: ${{ secrets.SOURCE_CHANNELS }}
          DESTINATION_CHANNEL: ${{ secrets.DESTINATION_CHANNEL }}
        run: |
          timeout 540 python main.py || echo "Script completed or timed out"

      - name: 5. Schedule next run
        run: |
          # منتظر 10 دقیقه بمان
          sleep 600
          # فایل تریگر برای اجرای بعدی
          echo "Next run scheduled at: $(date -d '+10 minutes')" > next_run.txt

      - name: 6. Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Schedule next run and update state [skip ci]"
          file_pattern: "last_message_ids.json next_run.txt"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions@github.com"
          commit_author: "GitHub Actions Bot <github-actions@github.com>"
